### ISSUE TITLE
Sync: downloaded note was unexpected

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#192] opened 2018-07-20 13:41 UTC
Taken out from #183:

Don't have steps to reproduce, but I'm getting this almost instantly after doing just few edits.
[downloaded-note-unexpected.zip](https://github.com/d1vanov/quentier/files/2214095/downloaded-note-unexpected.zip)

libquentier/src/synchronization/RemoteToLocalSynchronizationManager.cpp @ 2656 [Warn]: Internal error: the downloaded note was not expected, note: Note: { 
localUid: 952e1b11-c8e3-4c88-a87e-4b05a6b39e7c;

**Comment by d1vanov** [comment] 2018-07-20 14:16
Oh, this error suggests I screwed up the bookkeeping for notes pending downloading somewhere... Thanks, will take a look.

**Comment by d1vanov** [comment] 2018-07-26 04:45
Looked through the log, this error seems to be caused by sync stopping due to another error:
```
2018-07-20 15:38:12.084 CEST src/MainWindow.cpp @ 1815 [Debug]: MainWindow::onSynchronizationManagerFailure: Failed to add the data item fetched from the remote database to the local storage, can't do the partial update of note's resources, found invalid resource linked with note, Resource's data body is not set
```

**Comment by d1vanov** [comment] 2018-07-26 04:57
A bit more info, the error related to resources occurred as follows: a conflict between local and remote versions of the same note was detected. The local note contained attachments only within `RemoteLocalStorageManager` the binary data for these attachments were not present - i.e. they were not extracted from the local storage database, intentionally, because it seems there were no reason have them there. However, when attempting to create a local conflicting note, the request to add note to local storage was issued with "update resource binary data = true" flag. This update failed because the conflicting note had no resource binary data.

Perhaps I should process conflicting notes differently: currently the new conflicting note is created from the original local note, then the original local note is overridden with remove version. Then the new conflicting note is **added** i.e. created in the local storage database as a new note, and the overridden updated note is **updated** in the local storage database. Need to investigate if I could achieve the same through doing things in reverse order - remove fields like guid, updateSequenceNumber and such from the original local note, update it (without resources binary data updating) and then add the remote note as a new one.

**Comment by robert7** [comment] 2018-07-26 05:34
OK

**Comment by d1vanov** [comment] 2018-08-15 08:34
This one turned out to be harder to fix than I expected but I finally did it, the fix is in development branches of both libquentier and Quentier. I had to change some APIs within libquentier to make it work. Unit tests checking both the new APIs and the original issue are in place so things seem all settled here.

**Closed by d1vanov** 2018-08-15 08:34 UTC
Labels: bug, libquentier, synchronization
