### ISSUE TITLE
[bug] Cannot finish initial sync: nternal error: can't set the filter by saved search: failed to parse saved search query, Invalid query string: cannot parse datetime value: 20140201, 

### ISSUE THREAD

**Issue by timoc** [d1vanov/quentier#364] opened 2021-03-16 08:49 UTC
**Describe the problem**
Local repo initialization does not finish because it seems it cannot handle this saved search:
```
updated:20140201
```
**Steps to reproduce the problem**
1. Save the search "updated:20140201" in the evernote web client
2. Start Quentier and sync
3. Quentier hangs in sync.

**Expected behavior**
Quentier to start working.

**Environment info**
Please provide the information about the environment in which Quentier is run:
1. OS - Linux, 
2. In case of Linux: Kubuntu 20.10
3. Which version of Quentier do you use - 
quentier-qt5/groovy,now 0.5.0-1~ppa~quentier~202103011117~ubuntu20.10.1 amd64
4. Where did you install Quentier from - ppa (maybe a script can generate this info?)

**Comment by d1vanov** [comment] 2021-03-16 14:04
Hi, thank you very much for reporting it!
It is a little unexpected that this issue seems to affect the synchronization for you, it shouldn't really. But the root cause of this error seems clear, the fix is on the way.

**Comment by d1vanov** [comment] 2021-03-16 18:11
Pushed the fix for this problem with date parsing to both stable and unstable branches. PPA packages will be rebuilt and updated in several hours.

**Closed by d1vanov** 2021-03-16 18:11 UTC
Labels: bug

**Comment by timoc** [comment] 2021-03-16 18:41
Thanks. I removed the searches, but it still fails because the searches are still in the local note db
