### ISSUE TITLE
Add account ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by mjplimley** [d1vanov/quentier#377] opened 2021-11-19 19:22 UTC
Does somebody have a suggestion or fix for this error I'm getting when adding my Evernote account to a fresh appimage install of Quentier? I get this with Account type=Evernote and Evernote server=Evernote and clicking **OK**. See the attached log.

I didn't find anything in existing issues. I'm not using any sort of proxy. I can login to Evernote web from Linux, no problem. 

Ubuntu 20.04, Quentier 0.5.0 

Thanks,
Mark
[Quentier-log.txt](https://github.com/d1vanov/quentier/files/7572462/Quentier-log.txt)

**Comment by mjplimley** [comment] 2021-11-19 19:34
And I did clear cookies as suggested. Had no effect.

**Comment by d1vanov** [comment] 2021-11-19 19:39
Hi there.
It seems you are the first one getting such an error as I don't remember any occurrences of it in the past.
Have you tried on the version of Quentier from launchpad? It might in theory be some quirk of AppImage version.
Also, where exactly did you see this particular error - `ERR_TOO_MANY_REDIRECTS`? I can't see something like it in the attached log.

**Comment by d1vanov** [comment] 2021-11-19 19:44
Also from quick googling I found a recent enough Qt bug which is connected to QtWebEngine and Evernote - https://bugreports.qt.io/browse/QTBUG-96766. There's a [workaround](https://bugreports.qt.io/browse/QTBUG-96766) mentioned there. I'll try to reproduce the issue myself and in case of success will see if this workaround would make any difference.

**Comment by d1vanov** [comment] 2021-11-19 19:53
Just tried, the AppImage version indeed doesn't authenticate. But the version from launchpad seems to work well.
Not sure why this error appears for AppImage version, could be anything - from particularly unlucky Qt version used for AppImage build to a problem with OpenSSL (there used to be problems with it in the past).
Honestly, I consider the AppImage version of Quentier a "last resort" if one wants to try the app but there's no native package available. I've invested a considerablle amount of time in native packaging for various Linux distros so I would suggest to prefer them over the AppImage version.

**Comment by d1vanov** [comment] 2021-11-19 19:57
I'll try to update Qt version used for AppImage build and see if it would make any difference.

**Comment by mjplimley** [comment] 2021-11-19 20:00
Hey, thanks for the quick reply.

The error is in a pop-up window as soon as I click the OK button. The window title is Quentier. I hope this image works:
![image_2021-11-19_115142](https://user-images.githubusercontent.com/68918633/142683403-b6a10eff-3055-4b16-ac57-9569079d0465.png)

It does look like the QT bug you mention. I will try the launchpad version. If you can fix the AppImage version, I will test that also.

Thanks!

**Comment by mjplimley** [comment] 2021-11-19 20:33
Hmmm, I ran
```
sudo add-apt-repository ppa:d1vanov/quentier-stable
sudo apt-get update
sudo apt-get install quentier-qt5
```
but I get the same error on launching /usr/bin/quentier. I might have to wait until you rebuild, or upgrade to Ubuntu 21.04 and try that, unless you have a different suggestion.

Thanks again.

**Comment by d1vanov** [comment] 2021-11-19 21:37
Well, it's kinda unexpected, version from launchpad works for me.
If you start `/usr/bin/quentier` from the terminal, do you see any errors output when you try to authenticate?

**Comment by mjplimley** [comment] 2021-11-19 21:55
When I click OK to make the Evernote connection for setting up my account, this is written to the terminal window:
`qt5-WO7aOi/quentier-qt5-0.5.0/bin/quentier/src/MainWindow.cpp:2088 [Info] [quentier:main_window]: MainWindow::onAuthenticationFinished: success = false, error description = Can't authenticate to Evernote, account = `

**Comment by mjplimley** [comment] 2021-11-19 21:57
So to answer your question, I never get the opportunity to enter my login credentials. No pop-up or anything.

**Comment by d1vanov** [comment] 2021-11-20 05:48
Hmm, please clarify: with the version from launchpad you see the same error with "too many redirects" in the pop-up window as with the AppImage version, right?

**Comment by d1vanov** [comment] 2021-11-20 05:50
Or is it something different - like the pop-up window never opens in the first place?

**Comment by d1vanov** [comment] 2021-11-20 10:09
I tried to apply the workaround mentioned in the Qt bug page and it appears to work on [the unstable AppImage](https://github.com/d1vanov/quentier/releases/download/continuous-development/Quentier-development-x86_64.AppImage). Could you please test it and see if it works for you too? If yes, I'll push the fix to the stable version as well.

**Comment by d1vanov** [comment] 2021-11-22 17:09
Tried this fix I made on another machine and it worked there too. So I merged the fix to the stable branch as well. Launchpad version should update in a few hours and the stable [AppImage](https://github.com/d1vanov/quentier/releases/download/continuous-master/Quentier-master-x86_64.AppImage) is available for download now.
I'll close the issue as I believe it should be fixed now.  But if you still experience problems, feel free to reopen.

**Closed by d1vanov** 2021-11-22 17:09 UTC
Labels: bug, help wanted, question, authentication, AppImage
