### ISSUE TITLE
Sync with deleted note runs in infinite loop

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#191] opened 2018-07-20 13:06 UTC
From #183:

@d1vanov 
Per Evernote documentation, DATA_CONFLICT exception occurs on attempt to update note if it's deleted (i.e. deletion timestamp is present) but is still marked as active (note property). Probably I haven't tried to sync a deleted note myself and thus haven't implemented this properly. So what you see in the log is actually a wrong assumption of what this exception means which is also a bug. What should actually be fixed is setting the note's active property to false along with specifying the deletion timestamp.

@robert7
To reproduce: delete synced note and click on sync => infinite loop & sync doesn't really finish

**Comment by d1vanov** [comment] 2018-07-20 13:07
The reason is simple: `DATA_CONFLICT` exception gets misinterpreted - the sync algorithm thinks something changed on Evernote side and remote to local part of sync needs to be repeated. While in reality this error code means `active` flag is not reset to `false` for note marked as deleted one (through setting the deletion timestamp).

**Comment by robert7** [comment] 2018-07-20 13:09
ok. temp workaround is: undelete note in Quentier, sync, then delete in web client

**Comment by d1vanov** [comment] 2018-07-21 08:10
Pushed fixes to development: on libquentier side I forcefully set the "active" property of notes having deletion timestamp to false, on Quentier side I now change the "active" property of notes along with changing their deletion timestamps. Furthermore, removed wrong logic from libquentier which believed `DATA_CONFLICT` error code in response to note creation/update attempt means remote to local sync should be repeated. Checked on my test account: deleting a note and doing sync seems to work, restoring this note and doing sync again seems to work as well. Closing this one as I'm quite certain it should be fix now but if you manage to reproduce it again, please reopen.

**Closed by d1vanov** 2018-07-21 08:10 UTC
Labels: bug, libquentier, synchronization
