### ISSUE TITLE
I cannot get past sign-in with Evernote 

### ISSUE THREAD

**Issue by nowell-morris-la** [d1vanov/quentier#297] opened 2020-01-04 13:57 UTC
I am on Ubuntu 19.10 (xfce), and once I have signed in with Evernote and granted authorization, the credentials are not saved to keyring or wallet, and no connection is saved within Quentier.  I have gone through all the issues in here related to keyrings/wallets and have tried both gnome and kde's solutions to keyrings/wallets, but I have having no success.  At one point I tried running the whole OS with apparmor disabled as a troubleshooting measure, that didn't yield any results either.
![quentier](https://user-images.githubusercontent.com/53183382/71766647-5e109e00-2ebf-11ea-9af6-3bab7da42e95.png)
I am stumped.

**Comment by d1vanov** [comment] 2020-01-04 15:30
Hi there!
By description it seems the problem is caused by one of Quentier's dependent libraries, qtkeychain. It handles the communication with the platform's key storage service.
I can see you are trying to run Quentier AppImage, have you tried installing the deb package from launchpad instead? https://launchpad.net/~d1vanov/+archive/ubuntu/quentier-stable

**Comment by d1vanov** [comment] 2020-01-04 15:45
I think this error you are seeing is essentially frankosterfeld/qtkeychain#99. Currently for building the AppImage I use qtkeychain 0.8.0 but this error was fixed in a later version. I should update the version of qtkeychain used to build the AppImage.

If I'm correct you should be able to run Quentier from deb package successfully - it uses qtkeychain from distro's repository and Ubuntu 19.04 ships qtkeychain 0.9.1 which has this error fixed.

**Comment by d1vanov** [comment] 2020-01-05 12:48
I've updated both stable and unstable AppImages to use qtkeychain 0.9.1, so you can try new AppImage if for some reason you don't want to install the deb package.

**Comment by nowell-morris-la** [comment] 2020-01-09 02:01
You sir, are awesome!  I just tested with the AppImage.  It works now!  Thank you!

**Comment by d1vanov** [comment] 2020-01-09 04:05
Great, thank you for confirming that it works now!

**Closed by d1vanov** 2020-01-09 04:05 UTC
Labels: AppImage, bug, qtkeychain

**Comment by nowell-morris-la** [comment] 2020-01-10 03:46
Just as an FYI.  I went back to install via the ppa as you mentioned, and there is no build at launchpad for 19.10 (eoan).  There is 19.04 and before, but not a 19.10 :)  
Thanks for your hard work!

**Comment by d1vanov** [comment] 2020-01-10 03:59
Yes, I know, I'm already working on this, build for Eoan should become available in the near future.
