### ISSUE TITLE
Problem with app startup/shutdown (Ubuntu 16.04.4, AppImage)

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#182] opened 2018-07-15 18:53 UTC
Hi, 
I'm having a problem with running the quentier AppImage binary on Ubuntu 16.04.4.
I tried both version from development and master. 
See logs:
[Q-devel.log](https://github.com/d1vanov/quentier/files/2195996/Q-devel.log)
[Q-master.log](https://github.com/d1vanov/quentier/files/2195997/Q-master.log)

Then I tried the Ubuntu version from PPA (according to README). This installs and run, but refuses to end itself :)
What i did:
1, started app by "quentier"
2, gui starts
3, I end the program - gui disappear but the program is still running (I can confirm by ps -ef|grep quentier)
I even turned on TRACE in log window, but the log doesn't really show much:
2018-07-15 20:15:56.820 CEST libquentier/src/note_editor/SpellChecker_p.cpp @ 361 [Info]: No previously cached dic/aff files seem to
 actually exist anymore, re-scanning the system for dictionaries

(Windows binary worked :) )

Anyway ... I like your project! I found it today by accident. I spent last month quite much time by trying to revive the [Nixnote2](https://github.com/robert7/nixnote2) and I actually produced fist "alpha" binary release of "nixnote 2.1" on last Friday... Now I'm sad because it seems, I spend one month with wrong project, as your project seems to be in better shape then nixnote2... at least by first impression, did not yet had time to look at source (but I will do). From the quick look at the Windows version I'm missing some functions.. some of which I wanted to add in Nixnote. I can describe them in extra issue - if we agree, I can try to implement them.

**Comment by robert7** [comment] 2018-07-15 18:58
Further info:
the Windows version which I tried today  did show some "demo note", but the Ubuntu PPA version doesn't.

The Windows version displayed Evernote login box (but I did not really try to login as it was not on my computer). The Ubuntu version just does nothing on a sync attempt. So ... no login box no sync :)

Here is log with trace level:
[1-Quentier-log.txt](https://github.com/d1vanov/quentier/files/2196007/1-Quentier-log.txt)

**Comment by d1vanov** [comment] 2018-07-16 05:23
Hi.

Before I start answering: could you please create different issues for different problems in future? It seems you have piled together at least 5 unrelated issues here:

1. AppImages not starting
2. Quentier from PPA not stopping properly
3. Windows version displays Evernote login box although you had no intention to synchronize with Evernote
4. Ubuntu version doens't do anything on attempt to synchronize
5. Ubuntu version didn't show the welcome note

A GitHub issue is a place where the problem (or feature suggestion) can be discussed and clarified, where the logs are placed. You can even reference issues in commits and I do so most of the time. When one issue relates to 5 different problems, it becomes hard to track what's related to what.

Now, to the actual issues you are facing:

1. About AppImages not starting: it seems this is a packaging issue i.e. the one of linuxdeployqt. The log from both master and development versions contains the same error:
```
[8299:8674:0715/201810.851748:ERROR:nss_util.cc(712)] Error initializing NSS with a persistent database (sql:/home/rspiegel/.pki/nssdb): libsoftokn3.so: cannot open shared object file: No such file or directory
[8299:8674:0715/201810.851833:ERROR:nss_util.cc(201)] Error initializing NSS without a persistent database: NSS error code: -5925
[8299:8674:0715/201810.851852:FATAL:nss_util.cc(203)] nss_error=-5925, os_error=0
```
Quick googling of `AppImage Error initializing NSS with a persistent database` lead me to probonopd/linuxdeployqt#35 where I found the following advice in [this comment](https://github.com/probonopd/linuxdeployqt/issues/35#issuecomment-390199571):

> The Qt binary distribution works find on Ubuntu based systems, it just requires package libnss3

I actually have `libnss3` package installed and it still doesn't help. I tried to [extract](https://github.com/AppImage/AppImageKit/wiki/Extracting-AppImages) the AppImage and see whether it has a bundled libnss3. It indeed had its own bundled version of libnss3 and libnssutil3. After I removed them Quentier was able to start. So I guess something is wrong with packaging of `libnss3` and friends within the `AppImage`. It seems the following trick works to force the use of system libnss3 and friends:
```
LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/nss" ./Quentier-master-x86_64.AppImage
```
In the long run it seems I'd need to find some saner solution, probably try something like [this](https://github.com/probonopd/linuxdeployqt/issues/35#issuecomment-383003037).

2. About not stopping right away: actually it is kind of intended on the first run. When you start Quentier for the first time, it discovers nothing within its persistent storage (which was just created) and figures out it should scan the system for dictionaries to be used for spell checking within the note editor. Probably not the smartest idea but that's how it works now. The system scan is performed in the background thread. If you quit the application during the process, this background thread doesn't stop momentarily - it might take it some time to discover that it should actually abandon its job and stop. I'll try to look closer into this a bit later, however, I don't remember having this background thread running for unreasonably large time after I quit the app.

3. About Windows version displaying the login box unintentionally: I'm afraid you'd need to provide some steps to reproduce this issue if it's reproducible for you. Maybe you pressed some hotkey?

4. About Ubuntu version not showing the demo note: actually, this note should be created only when you launch Quentier for the first time so the default account is created for you. It might be that in your case this didn't work correctly because AppImage version did not start correcrly - maybe it still managed to set the "once started" flag so the subsequent run of Quentier from PPA (also, which PPA, master or development?) did not proceed with the demo note creation. If you haven't created anything within your local account yet, you can wipe `~/.quentier` folder to remove the existing persistence and start anew.

5. About Ubuntu version not synchronizing - as I understant, you are trying to use "Service" -> "Synchronize" menu and expect it to synchronize you with Evernote. Well, that's actually not how you are intended to proceed with synchronizing with Evernote. Quentier has two modes of working - either with local account or with Evernote account. On the first start the default local account is created for you. And in local accounts this menu entry should not actually be present in the first place since it makes no sense for local accounts, I need to remove this menu entry for local accounts. In order to log in to Evernote you need to pick "File" -> "Switch account" -> "Add account" and then choose Evernote account. It is explained in [this article](https://github.com/d1vanov/quentier/wiki/Brief-overview-of-Quentier-features) which I encourage you to read if you haven't done so already.

I'm glad you like this project. I'd be very happy to get some contributions, however, here are some guidelines for them:

1. First and foremost: before you start writing any code, create the issue, describe what you would like to do. Not just on the high level like "I want to sort searched notes by priority" but with implementation details. Like "I plan to add this thing to class A, so that it can be used from class B" and so on. Something like my description in #148. 
2. It's much, much better to make many small pull requests that a few large ones. Ideally a pull request should solve one problem or implement one feature and not touch a ton of other stuff on occasion.
3. Contributions should respect the project's [coding style](https://github.com/d1vanov/quentier/blob/master/CodingStyle.md).
4. Please don't include IDE project files into the pull requests - the project already has `CMakeLists.txt` which is supported natively by some IDEs and can generate project files for other IDEs. That should be enough for the project repo. Furthermore, some folks might want to customize their IDE projects somehow and having them under version control would only complicate that.

**Comment by d1vanov** [comment] 2018-07-16 05:46
Also, about the relations with Nixnote2: when I started this project, I did not know of Nixnote2 existence - it was in alpha state back then. I only learned about Nixnote2 existence after spending a year or so working on this project. After tinkering with Nixnote2 a bit I was not very much satisfied with it and decided to continue with this project nevertheless - partly due to sunk cost psychology and partly because I had other intentions for this project besides being the one and only free & open source desktop Evernote client. I discussed the relations with Nixnote2 in some more details in [this blog post](https://d1vanov.github.io/quentier/blog/helloworld).

**Comment by robert7** [comment] 2018-07-16 07:29
I already did read you "hello world" post yesterday :)

**Comment by robert7** [comment] 2018-07-16 07:56
OK. I will try next time create one issue per problem; but I supposed they a related someway.
1. I'll try later
2. OK. Maybe al log message informing about the background thread would be enough. Because like this it may be confusing to new users.
3. There is no issue with Windows version. I just did open the login dialog, but did really try to login (as I was on guest computer; I was just curious how the Win version looks)
4. OK i'll try later
5. OK my fault - I remembered that the Win version did show the login box so I was confused. But it could be related to point 1 not finished correctly

I did read you contribution document :)

**Comment by d1vanov** [comment] 2018-07-16 08:37
1. The experimental build which *might* have fixed the problem with AppImages is [ready](https://github.com/d1vanov/quentier/releases/download/continuous-development/Quentier-development-x86_64.AppImage) now. I haven't tested it yet and most probably I won't be able to do it until tomorrow. If you have time and if you'd like, you can give it a try sooner.
2. I actually remember that I did encounter such a problem myself but then I introduced a solution which in my case did make the background thread finish shortly after you quit the app. I'll give it one more try and see whether something can be done to make it sooner. Adding a trace log level might also be useful.
3. Ok
4. Ok
5. In the above mentioned development build I have removed the "Synchronize" menu entry from that menu + also removed a handful of other not actually implemented entries. Should have done that long before now but had consistently forgotten about it.

Sorry if I ask you to read too much stuff :blush: Hopefully that reading would be worth it in the long run.

**Comment by robert7** [comment] 2018-07-16 10:14
ok. I'm quite busy this week, but I will try to find some time.
the sync is running now, but it seems to be stuck at 50% already for ~few hours. I'll create new issue.

**Comment by robert7** [comment] 2018-07-16 11:35
I downloaded the AppImage you posted, but it doesn't work yet for me.

[2559:2597:0716/132438.110508:ERROR:nss_util.cc(712)] Error initializing NSS with a persistent database (sql:/home/rspiegel/.pki/nssdb): libsoftokn3.so: cannot open shared object file: No such file or directory
[2559:2597:0716/132438.110565:ERROR:nss_util.cc(201)] Error initializing NSS without a persistent database: NSS error code: -5925
[2559:2597:0716/132438.110571:FATAL:nss_util.cc(203)] nss_error=-5925, os_error=0

LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/nss" ./Quentier-development-x86_64.AppImage 
does work, but crashes on sync attempt

rspiegel@LP-RSPIEGEL:~/Downloads$ LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/nss" ./Quentier-development-x86_64.AppImage 
src/MainWindowSideBordersController.cpp @ 460 [Info]: Couldn't restore the persistent "Show left main window border" option, using the default one
src/MainWindowSideBordersController.cpp @ 471 [Info]: Couldn't restore the persistent "Show right main window border" option, using the default one
Dump path: /tmp/39c042e6-10ff-f51b-3d0f5072-3d67f829.dmp
Segmentation fault (core dumped)

[39c042e6-10ff-f51b-3d0f5072-3d67f829.dmp.tar.gz](https://github.com/d1vanov/quentier/files/2197402/39c042e6-10ff-f51b-3d0f5072-3d67f829.dmp.tar.gz)

...now I turned on TRACE log and it doesn't crash anymore

**Comment by d1vanov** [comment] 2018-07-16 11:37
Thanks for testing. Pity it didn't work, will try to find some other workaround. Also will look at the crash dump.

**Comment by robert7** [comment] 2018-07-16 11:48
it could be that "quentier not stopping properly" is due to Setting "close to tray" which is default true, but new users may not notice. I suggest switching the setting default value.

Further it crashed after closing the app from tray
libquentier/src/types/Note.cpp @ 560 [Debug]: Added 1 resources to note
libquentier/src/local_storage/LocalStorageManager_p.cpp @ 9053 [Debug]: Found tag local uid 8d7e7a1e-a761-4376-915d-0f88b0f2dd12 and tag guid 9b51e490-d68b-4c3b-b246-c0861cfc77f2 for note with local uid 2cde1c84-d1ac-4a57-b82c-5957b9f2a8d6
libquentier/src/local_storage/LocalStorageManager_p.cpp @ 9053 [Debug]: Found tag local uid 217101f4-2f81-4637-b9c8-231b5d095547 and tag guid 53fca4da-aec8-4734-9b96-ef23df3ed68a for note with local uid 2cde1c84-d1ac-4a57-b82c-5957b9f2a8d6
libquentier/src/types/Note.cpp @ 416 [Debug]: Added 2 tag guids to note
src/MainWindow.cpp @ 2833 [Info]: MainWindow::onQuitRequestedFromSystemTrayIcon
Dump path: /tmp/7ce45c87-485b-6723-7dd48e30-213f68bb.dmp
Segmentation fault (core dumped)
[7ce45c87-485b-6723-7dd48e30-213f68bb.dmp.tar.gz](https://github.com/d1vanov/quentier/files/2197437/7ce45c87-485b-6723-7dd48e30-213f68bb.dmp.tar.gz)

Here I used the last Quentier-development-x86_64.AppImage

Another problem is that for some reason, if the app is started as AppImage, then system theme is not respected - so gui has different fonts/colors. I think this is issue of linuxdeployqt, but maybe it could be useful to track it here as open issue? maybe there is workaround? should I create new issue for that?

**Comment by d1vanov** [comment] 2018-07-16 11:53
Although I haven't looked at the crash dumps yet, I suspect they have something to do with AppImage packaging. Or are you able to reproduce the crashes with PPA version as well?

About the non-respected system theme - it's an issue of AppImage format itself, not even the one of linuxdeployqt. The only solution the AppImage format has to offer is bundling whatever icon/font theme the app uses with it. I don't really like it and that's exactly why I bothered to create native packages for various distributions. From my POV AppImage in it very nature is a sort of a hack, a short term solution to give something to play with to early adopters while you haven't packaged your app properly. In fact, if problems with AppImage would continue, I might even discontinue distributing it since my time is too limited to come up with various workarounds for its issues.

**Comment by d1vanov** [comment] 2018-07-16 11:57
> it could be that "quentier not stopping properly" is due to Setting "close to tray" which is default true, but new users may not notice. I suggest switching the setting default value.

Ah, so that's not even the issue of that background thread I was thinking about. That's good to hear. I wouldn't like to change the default setting as, well, my experience shows few users bother to go to settings of any software, most just use whatever defaults they prefer. Probably a good solution would be to detect the very first time user closes the app and then offer him a choice - close to tray or quit. Then set the corresponding setting and use the chosen behavior later on until it's changed through the preferences dialog.

**Comment by d1vanov** [comment] 2018-07-17 04:47
It seems I was finally able to solve this notorious NSS error which prevented AppImage from running: simply removed libnss3.so and libnssutil3.so from the AppImage. It works on my machine (tm), you can give it a try as well: [Quentier-development-x86_64.AppImage](https://github.com/d1vanov/quentier/releases/download/continuous-development/Quentier-development-x86_64.AppImage).

**Comment by d1vanov** [comment] 2018-07-17 05:06
Also, I created a separate issue for more explicit main window closing handling: #185. So it seems the only relevant part of this issue now is AppImages not starting.

**Comment by robert7** [comment] 2018-07-17 13:31
The AppImage now works for me. Also the problem "Error initializing NSS without a persistent database" seems to be solved now. Thx.

**Comment by d1vanov** [comment] 2018-07-18 03:14
Thanks for checking, merged the fix for AppImages to master. As separate issues were created for other problems, closing this one.

**Closed by d1vanov** 2018-07-18 03:14 UTC
Labels: Linux, bug
