### ISSUE TITLE
Found a data item with empty name in the local storage: item type = Tag

### ISSUE THREAD

**Issue by stephanemouton** [d1vanov/quentier#322] opened 2020-05-19 19:08 UTC
Synchronization of Evernte account is interrupted and Error message in log is:
[Found a data item with empty name in the local storage: item type = Tag](url)

Ichecked with ID in the SQLite DB and the tag exists
I extracted log around error below

2020-05-19 10:17:34.795 CEST 0.5.0.git.1588655051.64c94447/lib/model/NoteModel.cpp:3715 [Trace]: [non-deleted notes] NoteModel::updateTagData: tag local uid = c2d8f5b3-5f4b-4ef8-9bb4-2ea2704d2f93
2020-05-19 10:17:34.795 CEST 0.5.0.git.1588655051.64c94447/bin/quentier/src/MainWindow.cpp:1788 [Error]: MainWindow::onSynchronizationManagerFailure: Found a data item with empty name in the local storage: item type = Tag
2020-05-19 10:17:34.795 CEST 0.5.0.git.1588655051.64c94447/bin/quentier/src/MainWindow.cpp:1324 [Debug]: MainWindow::scheduleSyncButtonAnimationStop
2020-05-19 10:17:34.795 CEST 0.5.0.git.1588655051.64c94447/bin/quentier/src/MainWindow.cpp:5549 [Debug]: MainWindow::setupRunSyncPeriodicallyTimer
2020-05-19 10:17:34.795 CEST 0.5.0.git.1588655051.64c94447/bin/quentier/src/MainWindow.cpp:2927 [Debug]: MainWindow::onRunSyncEachNumMinitesPreferenceChanged: 15
2020-05-19 10:17:34.795 CEST 0.5.0.git.1588655051.64c94447/bin/quentier/src/MainWindow.cpp:2073 [Debug]: MainWindow::onRemoteToLocalSyncStopped
2020-05-19 10:17:34.795 CEST 0.5.0.git.1588655051.64c94447/bin/quentier/src/MainWindow.cpp:1773 [Info]: MainWindow::onSynchronizationStopped
2020-05-19 10:17:34.795 CEST 0.5.0.git.1588655051.64c94447/bin/quentier/src/MainWindow.cpp:1773 [Info]: MainWindow::onSynchronizationStopped
2020-05-19 10:17:34.795 CEST libquentier-0.5.0.git.1581107324.f037573/src/synchronization/SynchronizationManager_p.cpp:261 [Debug]: SynchronizationManagerPrivate::stop
2020-05-19 10:17:34.795 CEST libquentier-0.5.0.git.1581107324.f037573/src/synchronization/SynchronizationManager_p.cpp:2163 [Debug]: SynchronizationManagerPrivate::tryUpdateLastSyncStatus
2020-05-19 10:17:34.795 CEST libquentier-0.5.0.git.1581107324.f037573/src/synchronization/RemoteToLocalSynchronizationManager.cpp:3019 [Debug]: RemoteToLocalSynchronizationManager::collectNonProcessedItemsSmallestUsns
2020-05-19 10:17:34.795 CEST libquentier-0.5.0.git.1581107324.f037573/src/synchronization/RemoteToLocalSynchronizationManager.cpp:3025 [Debug]: User own data sync chunks downloaded = false, all linked notebooks listed = false, linked notebook sync chunks downloaded = false

**Comment by d1vanov** [comment] 2020-05-19 19:32
Hi, thank you very much for reporting this! Would it be possible for you to post more detailed log somewhere? Also, was it a full sync or incremental sync? In the latter case, did you rename the tag or changed it locally otherwise (reparented etc)? Did it start only today or you haven't tried previously?

**Comment by d1vanov** [comment] 2020-05-20 06:19
I took a look into the code which can produce this error. There are several code branches which can produce it and it's crucial to know which one did in order to debug it. There should be a warning level log entry which says something like this:
```
src/synchronization/RemoteToLocalSynchronizationManager.cpp:N [Warn] Found a data item with empty name in the local storage: item type = Tag: <tag info>
```
In place of N there should be a line number. I would really like to know this line number. And frankly I would really like to see more parts of log around that place, ideally the whole log from the start of synchronization up to that point. It shouldn't contain much private info as notes are only downloaded later, after the sync of notebooks, tags and saved searches is completed.

Another question: where did you install Quentier from and which distro do you use? From commit hashes in paths it appears that you use more or less up to date version of Quentier but somewhat outdated version of libquentier:
```
$ git log f037573
commit f0375730d36fb0e69ba67728eea38884a572a25e (tag: continuous-master)
Merge: e3b4917 780e5ac
Author: Dmitry Ivanov <dm.vl.ivanov@gmail.com>
Date:   Fri Feb 7 23:28:44 2020 +0300

    Merge pull request #126 from d1vanov/feature/switch-MSVC-builds-to-ninja-on-AppVeyor-CI
    
    Switch MSVC builds to Ninja on AppVeyor CI
```
I'd recommend trying to sync with the most recent version. I did change a couple of things about the synchronization in the past few weeks so in the best case the issue might have been already fixed. But even if not, reproducing with most recent version would help in troubleshooting. If you don't want to mess with your package manager, you can try to run [AppImage](https://github.com/d1vanov/quentier/releases/download/continuous-master/Quentier-master-x86_64.AppImage) version of Quentier.

**Comment by stephanemouton** [comment] 2020-05-20 09:37
First: thank you for the attention paid to the problem!
I'll try to reach in my answer the level of precision or your questions. 

**About trace capture and RemoteToLocalSynchronizationManager.cpp warning**
I tried to trace the whole synchronization process but both with "save file" option and the application log files (Quentier-log.txt) I was unable to catch all the information.
Notably, I got the error message but was unable to find a line with

`src/synchronization/RemoteToLocalSynchronizationManager.cpp:N [Warn]`

I sent you the traces separately because logs contains tag lables and note titles. I will also try again to have a full capture of sync. 

**About version used**
I'm on Fedora 32.
I use the repository builds from https://software.opensuse.org//download.html?project=home%3Ad1vanov%3Aquentier-master&package=quentier which is a very convenient way to deploy.

I checked the repository description file and found that it did not use the `$releasever` in the URL and therefore still pointed to Fedora 31 repository.
Changing URL to `https://download.opensuse.org/repositories/home:/d1vanov:/quentier-master/$releasever/` would suppress that risk.

Anyway, I uninstalled the current version, removed the SQLite file, used the correct repository description file and reinstalled. Therefore everything should be as designed in the repositiory. 
I used the repository version to produce trace logs.
It is  0.5.0.git.1589873711.ffc7da82 so it corresponds to:
```
$ git log ffc7da82
commit ffc7da82c4e8008c7b10e6f4ebe1b5fd7e2e2b83 (HEAD -> master, tag: continuous-master, origin/master, origin/HEAD)
Author: Dmitry Ivanov <dm.vl.ivanov@gmail.com>
Date:   Tue May 19 10:35:11 2020 +0300
```

**Comment by d1vanov** [comment] 2020-05-20 15:49
> I sent you the traces separately because logs contains tag lables and note titles.

Ok, you can send me logs to dm.vl.ivanov@gmal.com, it's the same e-mail I use for git commits here. I promise I won't disclose any of your info from those logs, I just need to find out how this sync failure occurs.

In case you have already sent me something, please re-check, I haven't got anything in my inbox yet. Checked the spam folder too just in case.

**Comment by d1vanov** [comment] 2020-05-21 09:27
Thanks to provided logs, I found the root cause: when a tag is being searched for by name in the local storage, there's no proper account for diacritics. So if there are two or more tags which differ only by the presence/absence of diacritics in their names, the local storage would confuse between them. Probably this affects not only tags but also other data items i.e. notebooks and saved searches. I'll create a hotfix for this particular issue as soon as I can but then I'd need to carefully review all pieces of local storage code which can be affected by this issue and write tests to ensure they'd be gone for good.

**Comment by stephanemouton** [comment] 2020-05-21 10:12
Great job!
If I can be of any help in the test, I'm available

**Comment by stephanemouton** [comment] 2020-05-21 12:16
After renaming tag with conflicting diacritics I confirm it works
Tested with latest version in Fedora repository (f44179d)

**Comment by d1vanov** [comment] 2020-05-21 12:19
Great, thanks!
Meanwhile I reproduced the problem within my own Evernote account, committed a simple fix and verified that it solves the problem. Pushed the fix to both master and development branches, builds should follow soon enough.

Won't close this issue right now as I still need to look for similar issues in other places within the local storage code + write tests to ensure the problem won't reappear later on.

**Comment by d1vanov** [comment] 2020-05-22 14:44
Notebooks and saved searches are not affected by a similar bug. Wrote unit tests to ensure that and to ensure the fix for tags works properly. Pushed the fix to both master and development branches, updated all distributed packages including Windows ones.

**Closed by d1vanov** 2020-05-22 14:44 UTC
Labels: bug, libquentier, synchronization
