### ISSUE TITLE
Sync fails if the "Sync" toolbar button is clicked from just new note

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#199] opened 2018-07-21 16:06 UTC
To reproduce:

1. click on new note
2. enter some text in body "AA"
3. enter some text in title e.g. "AA"
4. click on Sync button => sync fails as someway the note body is still empty and doesn't contain the text "AA"

src/MainWindow.cpp @ 1824 [Debug]: MainWindow::onSynchronizationManagerFailure: Failed to send new and/or mofidied notes to Evernote service, ENML_VALIDATION exception during the attempt to create a note, note's content doesn't validate against DTD

![screen_20180721_08](https://user-images.githubusercontent.com/1135218/43037697-97bbe2e2-8d10-11e8-9a1c-8e72401fa8ce.png)

![screen_20180721_09](https://user-images.githubusercontent.com/1135218/43037698-9c30a754-8d10-11e8-9be5-1835b262d155.png)

![screen_20180721_10](https://user-images.githubusercontent.com/1135218/43037705-cc9613c0-8d10-11e8-8256-87b66b3808cd.png)

**Comment by d1vanov** [comment] 2018-07-21 16:34
Damn, of all things I hoped to never see the ENML problem. I can see the save button is active on all screenshots which means the note content isn't saved. Can you reproduce it after pressing the save button? Also please attach trace logs.

**Comment by robert7** [comment] 2018-07-21 17:18
When I press on "save", then I can't reproduce .
Here is trace log (without pressing the "Save" button): 
![screen_20180721_18]
[trace-log.zip](https://github.com/d1vanov/quentier/files/2216350/trace-log.zip)

But :) I didn't even know, there is a "Save" button before... I think it is a bit against the Evernote philosophy - I never seen a "Save" button in any other Evernote client (Evernote desktop, Evernote web, Evernote iOS/Android => there is no Save button, all is saved automatically). So I guess new users will expect this and this can cause confusion. So I would recommend to remove the button and save automatically. You just type and its saved .. instantly.

![screen_20180721_18](https://user-images.githubusercontent.com/1135218/43038527-cf446a54-8d1a-11e8-8850-1d61d8db0de3.png)

**Comment by d1vanov** [comment] 2018-07-21 19:34
The automatic saving is already in place actually, only it seems now it doesn't work in all situations in which it's necessary. Saving *instantly* is easier said than done - if you start thinking about it, it's not wise to attempt saving the entire note each time you press some key on the keyboard while typing a note - you'd waste a lot of system resources (and if you have a SSD drive, this is going to hurt it sufficiently enough) and hurt the performance of the note editor so that it'd become sluggish and unresponsive thus driving you mad. So instead of saving "instantly", saving occurs periodically and attempts to not get in the way of user typing something into the note.

Perhaps automatic saving should occur before the sync is started and probably even each time the note editor loses focus. Although I thought the latter one is already implemented, don't remember now, need to look into the source code to find out for sure.

I actually shamelessly stole the idea for "save" button from baumgarr/nixnote2#261. Casual users indeed should not be forced to manually save the note in normal circumstances. However, it is handy to have a way to force saving the note if for some reason it didn't work automatically. It is also handy to be able to see the disabled save button and thus conclude that the note has already been saved. So I intend to keep this button.

I should continue writing both user and developer docs for Quentier so that things like this saving logic is described somewhere but with all the issues you've recently found I have completely no time for this anymore :worried: :blush:

**Comment by d1vanov** [comment] 2018-07-21 19:37
Regarding `ENML_VALIDATION` - I was hoping to never see it because I actually validate note's ENML on saving it, in particular, after the conversion of note editor's HTML to ENML. If the note is not valid, some auto-fixing is attempted, if it fails, the note simply refuses to be saved. So you learn about the problem with formatting long before you try to sync - something which was a perpetual problem in Nixnote2 as it didn't mind doing client side validation.

This error code in your case seems to originate from the fact that I insert some actually empty ENML into the new note (like `<enml></enml>`, don't remember the particular contents now) and apparently it doesn't validate against the DTD. Yes, before the note is saved for the first time and the conversion from HTML to ENML is performed, no client side validation occurs.

**Comment by robert7** [comment] 2018-07-22 09:49
>Saving instantly is easier said than done - if you start thinking about it, it's not wise to attempt saving the entire note each time you press some key 

Of course - in a desktop app, it would be enough to save like in 30 seconds after the last keypress - or something like that. I think the web client is doing the same. It doesn't save after each key stroke.

>However, it is handy to have a way to force saving the note if for some reason it didn't work automatically. It is also handy to be able to see the disabled save button and thus conclude that the note has already been saved. So I intend to keep this button.

OK. Maybe later we can add some config for user to be able to hide some unused toolbar buttons.

>something which was a perpetual problem in Nixnote2 as it didn't mind doing client side validation.

Yes. the HTML to ENML conversion in nixnote was quite terrible. I actually rewritten biggest part of it, but its not 100% finished. And now apparently I will never finish it.

**Comment by d1vanov** [comment] 2018-07-25 04:57
This one should be fixed now in development: first, I fixed the default ENML for new note: turned out, Evernote wanted the starting xml tag and doctype declaration to accept blank enml like `<en-note><div></div></en-note>`. Second, I now save the contents of note editors to notes automatically before starting the sync. Please report if you'd still experience this problem.

**Closed by d1vanov** 2018-07-25 04:57 UTC
Labels: bug
